
default:
    image: openjdk:16-slim
    before_script:
        - java -version
        - | 
            # Install sbt
            mkdir -p /etc/apt/sources.list.d/
            apt-get update -y
            apt-get install apt-transport-https gnupg -y
            echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
            apt-get update -y
            apt-get install sbt -y
        - sbt sbtVersion

sbt tests:
    script:
        - sbt test coverageReport
    artifacts:
        untracked: true
        expire_in: 30 days
