default:
    image: openjdk:16-slim
    before_script:
        - java -version
        - | 
            # Install sbt
            mkdir -p /etc/apt/sources.list.d/
            apt-get update -qq
            apt-get install -qq apt-transport-https gnupg curl 
            echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
            apt-get update -qq
            apt-get install sbt -qq
        - sbt sbtVersion

sbt_dependencyStats:
  script:
    - sbt dependencyTree dependencyStats

sbt_tests:
    rules:
        - changes:
            - "**/**/*.scala"
            - "**/**/*.sbt"
    script:
        - sbt test coverageReport
    artifacts:
        untracked: true
        expire_in: 30 days
        reports:
            junit: target/unit-tests-reports/TEST*.xml
            cobertura: target/scala-2.13/coverage-report/cobertura.xml
